<a href="https://colab.research.google.com/github/BambiPK/mydata_portfolio/blob/main/NPPD_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Numerical python
import numpy as np

In [ ]:
np.arange(10)+1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#2D Array
n2 = np.array([
    [1,2],
    [3,4]
])

In [ ]:
n2

array([[1, 2],
       [3, 4]])

In [ ]:
#Matrix * Matrix
#.dot notation
m1 = np.array([[1,2], [5,5]])
m2 = np.array([[4,2],[1,2]])

In [ ]:
np.dot(m1,m2)

array([[ 6,  6],
       [25, 20]])

In [ ]:
#import pandas for manage dataframe
import pandas as pd

In [ ]:
#read data from csv file
url = "https://gist.githubusercontent.com/seankross/a412dfbd88b3db70b74b/raw/5f23f993cd87c283ce766e7ac6b329ee7cc2e1d1/mtcars.csv"

mtcars = pd.read_csv(url)

In [ ]:
mtcars.shape

(32, 12)

In [ ]:
mtcars

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0   
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0   
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0   
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0   
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0   
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0   
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1   
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1   
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1   
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0   
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0   
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0   
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0   
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1   
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1   
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1   
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1   
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1   
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1   
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1   

    gear  carb  
0      4     4  
1      4     4  
2      4     1  
3      3     1  
4      3     2  
5      3     1  
6      3     4  
7      4     2  
8      4     2  
9      4     4  
10     4     4  
11     3     3  
12     3     3  
13     3     3  
14     3     4  
15     3     4  
16     3     4  
17     4     1  
18     4     2  
19     4     1  
20     3     1  
21     3     2  
22     3     2  
23     3     4  
24     3     2  
25     4     1  
26     5     2  
27     5     2  
28     5     4  
29     5     6  
30     5     8  
31     4     2

In [ ]:
mtcars.head()

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [ ]:
df = mtcars[ ["model", "mpg", "hp"] ].tail(3)

In [ ]:
#new column
df["mpg_dbl"] = df["mpg"]*2

In [ ]:
df.head() #or just df is okay

model   mpg   hp  mpg_dbl
29   Ferrari Dino  19.7  175     39.4
30  Maserati Bora  15.0  335     30.0
31     Volvo 142E  21.4  109     42.8

In [ ]:
df["mpg"].sum()

56.1

In [ ]:
df["mpg"].mean()

18.7

In [ ]:
#To update column name
colnames = list(df.columns)
colnames[0] = "New Model"
df.columns = colnames

In [ ]:
df.head()

New Model   mpg   hp  mpg_dbl
29   Ferrari Dino  19.7  175     39.4
30  Maserati Bora  15.0  335     30.0
31     Volvo 142E  21.4  109     42.8

In [ ]:
#Filter traditional
mtcars[ (mtcars["mpg"]>30) & (mtcars["hp"] >100) ]

model   mpg  cyl  disp   hp  drat     wt  qsec  vs  am  gear  carb
27  Lotus Europa  30.4    4  95.1  113  3.77  1.513  16.9   1   1     5     2

In [ ]:
#Modern filter use .query in pandas
#condition used to filter dataframe
mtcars.query("mpg > 30 and hp > 100")

model   mpg  cyl  disp   hp  drat     wt  qsec  vs  am  gear  carb
27  Lotus Europa  30.4    4  95.1  113  3.77  1.513  16.9   1   1     5     2

In [ ]:
#Aggregate + Group by
#Read data

store = pd.read_csv("store.csv")

FileNotFoundError: ignored

In [ ]:
store.shape

(9994, 21)

In [ ]:
#1 Clean data by renew column name
col_names = list(store.columns)

In [ ]:
clean_col_names = [col.lower().replace(" ", "_").replace("-","_") for col in col_names]

In [ ]:
store.columns = clean_col_names

In [ ]:
store.head()

row_id        order_id  order_date   ship_date       ship_mode customer_id  \
0       1  CA-2016-152156   11/8/2016  11/11/2016    Second Class    CG-12520   
1       2  CA-2016-152156   11/8/2016  11/11/2016    Second Class    CG-12520   
2       3  CA-2016-138688   6/12/2016   6/16/2016    Second Class    DV-13045   
3       4  US-2015-108966  10/11/2015  10/18/2015  Standard Class    SO-20335   
4       5  US-2015-108966  10/11/2015  10/18/2015  Standard Class    SO-20335   

     customer_name    segment        country             city  ...  \
0      Claire Gute   Consumer  United States        Henderson  ...   
1      Claire Gute   Consumer  United States        Henderson  ...   
2  Darrin Van Huff  Corporate  United States      Los Angeles  ...   
3   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...   
4   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...   

  postal_code  region       product_id         category sub_category  \
0       42420   South  FUR-BO-10001798        Furniture    Bookcases   
1       42420   South  FUR-CH-10000454        Furniture       Chairs   
2       90036    West  OFF-LA-10000240  Office Supplies       Labels   
3       33311   South  FUR-TA-10000577        Furniture       Tables   
4       33311   South  OFF-ST-10000760  Office Supplies      Storage   

                                        product_name     sales  quantity  \
0                  Bush Somerset Collection Bookcase  261.9600         2   
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400         3   
2  Self-Adhesive Address Labels for Typewriters b...   14.6200         2   
3      Bretford CR4500 Series Slim Rectangular Table  957.5775         5   
4                     Eldon Fold 'N Roll Cart System   22.3680         2   

   discount    profit  
0      0.00   41.9136  
1      0.00  219.5820  
2      0.00    6.8714  
3      0.45 -383.0310  
4      0.20    2.5164  

[5 rows x 21 columns]

In [ ]:
store["sales"].sum()

2297200.8603000003

In [ ]:
result = store.groupby(["segment", "category"])["sales"].sum().reset_index()

In [ ]:
store.groupby("segment")["sales"].agg(["sum","mean","std"]).reset_index()

segment           sum        mean         std
0     Consumer  1.161401e+06  223.733644  585.516175
1    Corporate  7.061464e+05  233.823300  599.410408
2  Home Office  4.296531e+05  240.972041  755.516379

In [ ]:
result.to_csv("agg_data.csv")

In [ ]:
#Read data from SQL data base
import sqlite3
import pandas as pd


In [ ]:
#Create connection
con = sqlite3.connect("chinook.db")

df = pd.read_sql("SELECT * FROM CUSTOMERS WHERE COUNTRY = 'USA'", con)

df.head()

#close connection
con.close()

In [ ]:
df.head()

CustomerId FirstName LastName                Company  \
0          16     Frank   Harris            Google Inc.   
1          17      Jack    Smith  Microsoft Corporation   
2          18  Michelle   Brooks                   None   
3          19       Tim    Goyer             Apple Inc.   
4          20       Dan   Miller                   None   

                     Address           City State Country  PostalCode  \
0  1600 Amphitheatre Parkway  Mountain View    CA     USA  94043-1351   
1            1 Microsoft Way        Redmond    WA     USA  98052-8300   
2               627 Broadway       New York    NY     USA  10012-2612   
3            1 Infinite Loop      Cupertino    CA     USA       95014   
4       541 Del Medio Avenue  Mountain View    CA     USA   94040-111   

               Phone                Fax                    Email  SupportRepId  
0  +1 (650) 253-0000  +1 (650) 253-0000       fharris@google.com             4  
1  +1 (425) 882-8080  +1 (425) 882-8081  jacksmith@microsoft.com             5  
2  +1 (212) 221-3546  +1 (212) 221-4679        michelleb@aol.com             3  
3  +1 (408) 996-1010  +1 (408) 996-1011         tgoyer@apple.com             3  
4  +1 (650) 644-3358               None      dmiller@comcast.com             4